Change of paradigm. Now using sockets to connect directly without check_mk.

diff --git a/xymon b/xymon
--- a/xymon
+++ b/xymon
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Check Xymon hosts and services for obsidian
+# Check Xymon hosts and services for check_mk
 #
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 #
@@ -37,18 +37,14 @@ print_usage() {
   echo "${PROGNAME}"
   echo "Version: ${VERSION}"
   echo ""
-  echo "Usage: ${PROGNAME} -H | -S <host> | -G <host> <service> | -v | -h"
+  echo "Usage: ${PROGNAME} -v | -h"
   echo ""
   echo "  -h  Show this page"
   echo "  -v  Software version"
-  echo "  -H  List all hosts. Default"
-  echo "  -S  List all services from <host>"
-  echo "  -G  Get <service> details from <host>"
   echo ""
 }
 
 # Parse parameters
-REPORTOPTION="-H"
 while [ $# -gt 0 ]; do
   case "$1" in
     -h)
@@ -58,21 +54,6 @@ while [ $# -gt 0 ]; do
     -v)
       print_version
       exit $STATE_OK
-      ;;
-    -H)
-      REPORTOPTION=$1
-      ;;
-    -S)
-      REPORTOPTION=$1
-      shift
-      REPORTHOST=$1
-      ;;
-    -G)
-      REPORTOPTION=$1
-      shift
-      REPORTHOST=$1
-      shift
-      REPORTSERVICE=$1
       ;;
     *)
       echo "Unknown argument: $1"
@@ -232,6 +213,7 @@ rrd_by_service() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Xymon configuration
 #
+#XYMSRV="127.0.0.1"
 # Try to find where is Xymon installed:
 XYMONSERVERROOT=$(ps ax|awk '{print $5;}' | grep "^.*/server/bin/xymonlaunch.*" | sed "s/\/server\/bin\/xymonlaunch//g")
 if [[ -z $XYMONSERVERROOT ]]; then
@@ -246,97 +228,73 @@ if [[ ! $? ]]; then
   exit $STATE_UNKNOWN
 fi
 
+#RRDHOME="$XYMONSERVERROOT/data/rrd"
+#XYMONRRDS this is defined in MAINCFGFILE, is equal to RRDHOME
+#XYMONHOSTS=$(grep "^[0-9a-zA-Z].*" $XYMONSERVERROOT/server/etc/hosts.cfg | awk '{print $2;}')
+
+
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Xymon checks
 #
 
-case "$REPORTOPTION" in
-  -H)
-    # Report hosts:
-    QUERYBOARD="xymondboard fields=hostname"
-    XYMONBOARD=$($XYMONSERVERROOT/server/bin/xymon $XYMSRV "$QUERYBOARD" | sort -u)
-    if [[ ! $? ]]; then
-      echo "ERROR: Couldn't check for hosts on xymondboard." >&2
-      exit $STATE_UNKNOWN
-    else
-      for host in $XYMONBOARD; do
-        echo $host
+# Query Xymon for last checks of each service:
+QUERYBOARD="xymondboard fields=hostname,testname,color,line1"
+XYMONBOARD=$($XYMONSERVERROOT/server/bin/xymon $XYMSRV "$QUERYBOARD" | sed "s/<\!\-\-.*\-\->//g")
+if [[ ! $? ]]; then
+  echo "ERROR: Couldn't check for xymondboard." >&2
+  exit $STATE_UNKNOWN
+fi
+# Values in board are separated by '|' (pipes).
+# Each line has: hostname|testname|color|line1.
+echo "$XYMONBOARD" | while read check; do
+  # Parse host:
+  host=$(echo $check | awk -F'|' '{print $1;}')
+  # Parse service (test):
+  testname=$(echo $check | awk -F'|' '{print $2;}')
+  # Parse state color:
+  color=$(echo $check | awk -F'|' '{print $3;}')
+  # Parse service output status:
+  line1=$(echo $check | awk -F'|' '{print $4;}')
+  if [[ -z $line1 ]]; then
+    # This means that Xymon is not reporting any text in service status. So I put the color:
+    line1="$color"
+  fi
+  # We need the state to be a number: 0 (ok), 1 (warn), 2 (crit) or 3 (unkn):
+  state=$(color_to_code $color)
+  # Check if there are rrd files for this service:
+  rrdfiles=$(rrd_by_service $host $testname $XYMONRRDS)
+  perf=""
+  if [[ $rrdfiles ]]; then
+    # This means there is at least one metric for this service.
+    # Now, if we have more than one metric, we should create one service per metric.
+    rrdcount=$(echo "${rrdfiles}"|awk -F'##' '{print NF-1;}')
+    # Replace '##' with spaces, so for can loop over the files:
+    rrdfiles=$(echo "${rrdfiles}"|sed "s/##/ /g")
+    if [[ $rrdcount -gt 1 ]]; then
+      # This means there is more than one metric.
+      for file in $rrdfiles; do
+      #if [[ $perf ]]; then
+        #perf="${perf}|"
+      #fi
+        metric=$(echo "${file}"|sed "s/=.*$//g")
+        rrdfile=$(echo "${file}"|sed "s/^.*=//g")
+        value=$(rrd_last_value $rrdfile)
+        perf="${metric}=${value}"
+        echo "$state ${host}_${testname}_${metric} $perf $line1"
       done
-      exit $STATE_OK
-    fi
-    ;;
-  -S)
-    # Report services for a host:
-    QUERYBOARD="xymondboard fields=testname host=$REPORTHOST"
-    XYMONBOARD=$($XYMONSERVERROOT/server/bin/xymon $XYMSRV "$QUERYBOARD" | grep -v "trends" | grep -v "clientlog")
-    if [[ ! $? ]]; then
-      echo "ERROR: Couldn't check for $REPORTHOST services on xymondboard." >&2
-      exit $STATE_UNKNOWN
     else
-      for service in $XYMONBOARD; do
-        rrdfiles=$(rrd_by_service $REPORTHOST $service $XYMONRRDS)
-        if [[ $rrdfiles ]]; then
-          # This means there is at least one metric for this service.
-          # Now, if we have more than one metric, we should create one service per metric.
-          rrdcount=$(echo "${rrdfiles}"|awk -F'##' '{print NF-1;}')
-          # Replace '##' with spaces, so for can loop over the files:
-          rrdfiles=$(echo "${rrdfiles}"|sed "s/##/ /g")
-          if [[ $rrdcount -gt 1 ]]; then
-            # This means there is more than one metric.
-            for file in $rrdfiles; do
-              metric=$(echo "${file}"|sed "s/=.*$//g")
-              echo "${service}_${metric}"
-            done
-          else
-            # This means there is only one metric.
-            echo "${service}"
-          fi
-        else
-          # In this case we only have one service and no perf data.
-          echo "${service}"
-        fi
-      done
-      exit $STATE_OK
-    fi
-    ;;
-  -G)
-    # Report service status details:
-    # Separate service and metric:
-    METRIC=$(echo "$REPORTSERVICE" | sed "s/^.*_//g")
-    REPORTSERVICEFRONT=$(echo "$REPORTSERVICE" | sed "s/_.*$//g")
-    QUERYBOARD="xymondboard fields=color,line1 host=$REPORTHOST test=$REPORTSERVICEFRONT"
-    XYMONBOARD=$($XYMONSERVERROOT/server/bin/xymon $XYMSRV "$QUERYBOARD" | sed "s/<\!\-\-.*\-\->//g")
-    if [[ ! $? ]]; then
-      echo "ERROR: Couldn't check for xymondboard." >&2
-      exit $STATE_UNKNOWN
-    fi
-    # Values in board are separated by '|' (pipes).
-    color=$(echo $XYMONBOARD | awk -F'|' '{print $1;}')
-    line1=$(echo $XYMONBOARD | awk -F'|' '{print $2;}')
-    if [[ -z $line1 ]]; then
-      # This means that Xymon is not reporting any text in service status. So I put the color:
-      line1="$color"
-    fi
-    # We need the state to be a number: 0 (ok), 1 (warn), 2 (crit) or 3 (unkn):
-    state=$(color_to_code $color)
-    # Check if there is a rrd file for this service:
-    rrdfile=$(rrd_by_service $REPORTHOST $REPORTSERVICEFRONT $XYMONRRDS | grep $METRIC | sed "s/^.*=//g")
-    if [[ $rrdfile ]]; then
-      # This means there is a metric for this service.
-      # Eliminate '##' :
-      rrdfile=$(echo "${rrdfile}"|sed "s/##//g")
+      # This means there is only one metric.
+      metric=$(echo "${rrdfiles}"|sed "s/=.*$//g")
+      rrdfile=$(echo "${rrdfiles}"|sed "s/^.*=//g")
       value=$(rrd_last_value $rrdfile)
-      perf="${METRIC}=${value}"
-    else
-      # In this case we only have one service and no perf data.
-      # So I set perf data to availability:
-      perf="available=$(color_to_avail $color)"
+      perf="${metric}=${value}"
+      echo "$state ${host}_${testname} $perf $line1"
     fi
-    echo "$state|$line1|$perf"
-    ;;
-  *)
-    echo "No report option"
-    ;;
-esac
-
+  else
+    # In this case we only have one service and no perf data.
+    # So I set perf data to availability:
+    perf="available=$(color_to_avail $color)"
+    echo "$state ${host}_${testname} $perf $line1"
+  fi
+done
 
